### ISSUE TITLE
Cannot build the frontend website

### ISSUE THREAD

**Issue by hugogirard** [microsoft/AzureSearch_JFK_Files#103]
Hi,

So the initializer work perfectly but I cannot build the frontend react website, I tried npm run build:prod and npm run build:dev and it throw error.

In the npm run build:dev I got more context

![image](https://user-images.githubusercontent.com/64166891/107992850-91b96500-6fa7-11eb-970d-fe437ae0c13c.png)

I am using node v14.15.5

**Comment by Careyjmac** [comment]
#105  should hopefully fix this, let us know if it doesn't
