### ISSUE TITLE
Failed when building web frontend with "npm run build:prod"

### ISSUE THREAD

**Issue by teo-ma** [microsoft/AzureSearch_JFK_Files#104]
Hi experts，

I pull the JFK source code on my windows laptop and use VS 2019 enterprise to deploy onto Azure.I got failed when  building web frontend with"**npm install**" and  "**npm run build:prod**" on step 13.And I tried Node JS version node-v14.15.5,node-v15.8.0,both of them do not work.below are screenshots for errors,

![image](https://user-images.githubusercontent.com/16115524/108149243-5cc72280-710d-11eb-8a67-7352c2632159.png)
![image](https://user-images.githubusercontent.com/16115524/108149264-6b153e80-710d-11eb-9229-e8fb72496b9b.png)

But it ever worked on two months ago (Dec 2020),any suggestions would be much appreciated.

Thanks,

Teo

**Comment by Careyjmac** [comment]
#105  should hopefully fix this, let us know if it doesn't
