### ISSUE TITLE
Current indexer status: TransientFailure

### ISSUE THREAD

**Issue by manandakrishna** [microsoft/AzureSearch_JFK_Files#109]
Hello Team,

After website deployment. Indexer is failing. I verified in search indexer and below is the error from indexer.
Indexer Error:
Could not execute skill because the Web Api request failed.

localId=https%3a%2f%2fazsjfkfiles.blob.core.windows.net%2fjfkfiles%2fcastro%2520operation%2fdocid-32105760.pdf&documentKey=https%3a%2f%2fazsjfkfiles.blob.core.windows.net%2fjfkfiles%2fcastro%2520operation%2fdocid-32105760.pdf
----------------------------------------------------------
Initializer log

Website deployment accepted.  Waiting for deployment to complete...
Current website deployment status: 
Website deployment completed.
Website url: https://xxxxxxxx.azurewebsites.net/
Waiting for indexing to complete...
Current indexer status: InProgress
Current indexer status: InProgress
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #11
Current indexer status: InProgress
Current indexer status: InProgress
Current indexer status: InProgress
Current indexer status: TransientFailure

**Comment by Careyjmac** [comment]
Looks like this is a legit error with the Azure Functions unfortunately, I will see if I can find some time to look into it more in depth.

Web Api response status: 'InternalServerError', Web Api response details: '<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title> HTTP Error 500.31 - ANCM Failed to Find Native Dependencies </title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
                font-size: .813em;
                color: #222;
                background-color: #fff;
            }

            h1, h2, h3, h4, h5 {
                /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
                font-weight: 100;
            }

            h1 {
                color: #44525e;
                margin: 15px 0 15px 0;
            }

            h2 {
                margin: 10px 5px 0 0;
            }

            h3 {
                color: #363636;
                margin: 5px 5px 0 0;
            }

            code {
                font-family: Consolas, "Courier New", courier, monospace;
            }

            body .titleerror {
                padding: 3px 3px 6px 3px;
                display: block;
                font-size: 1.5em;
                font-weight: 100;
            }

            a {
                color: #1ba1e2;
                text-decoration: none;
            }

                a:hover {
                    color: #13709e;
                    text-decoration: underline;
                }

            li {
                margin: 5px;
            }

        </style>
    </head>
    <body>
        <h1> HTTP Error 500.31 - ANCM Failed to Find Native Dependencies </h1>

        <h2> Common solutions to this issue: </h2>The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.

        

        <h2> Troubleshooting steps: </h2>

        <ul>
            <li> Check the system event log for error messages </li>
            <li> Enable logging the application process' stdout messages </li>
            <li> Attach a debugger to the application process and inspect </li>
        </ul>

        <h2>
            For more information visit:
             <a href="https://go.microsoft.com/fwlink/?LinkID=2028526"> <cite> https://go.microsoft.com/fwlink/?LinkID=2028526 </cite> </a>
        </h2>
    </body>
</html>
'
