### ISSUE TITLE
website could not Search the result after change website name 

### ISSUE THREAD

**Issue by Scarlettliuyc** [microsoft/AzureSearch_JFK_Files#114]
hi team,
We have a customer build this project and changed the source data for storage account. Confirmed about the web app username and password. 
When deleted the old resources from example , there shows error in this web page, and could not search for the results
![image](https://user-images.githubusercontent.com/69622329/129169919-bc192083-7171-4d54-ad21-c0e9d4300d4e.png)
But it could search in Search demo api
![image](https://user-images.githubusercontent.com/69622329/129170128-097da679-6056-4784-9460-811265a9be8a.png)

could you please tell us any other configuration in the program that link with example.
when tried to **npm run build:prod** again ,there are error about 401 
![image](https://user-images.githubusercontent.com/69622329/129170565-23dd68c3-4ebb-4b0c-b923-df0b30783eef.png)

**Comment by Careyjmac** [comment]
If you deleted and recreated the demo, make sure you update all of the keys and such in your App.config file. You also need to make sure you reset the [.env file](https://github.com/microsoft/AzureSearch_JFK_Files/blob/master/frontend/.env) to its original state in order for the website credentials to get reset appropriately, and then make sure you start the instructions over from scratch (i.e. rebuild the website locally at the appropriate step)
