### ISSUE TITLE
Error while creating the indexer

### ISSUE THREAD

**Issue by salils123** [microsoft/AzureSearch_JFK_Files#119]
Error creating indexer: Error with data source: Error processing blob 'https://azsjfkfiles.blob.core.windows.net/jfkfiles/castro%20operation/docid-32105760.pdf': This request is not authorized to perform this operation using this resource type.  Please adjust your data source definition in order to proceed.

**Comment by mattmsft** [comment]
Hi Salil,

We've confirmed there's an issue with authentication to the JFK Files blob storage container. We'll be taking a look at this issue on our end and creating a fix. Sorry for the inconvenience

Thanks,
Matt

**Comment by jennifermarsman** [comment]
I apologize for the inconvenience!  This should fix it: https://github.com/microsoft/AzureSearch_JFK_Files/pull/120

**Comment by mattmsft** [comment]
Hi @salils123,

We believe we have fixed this issue. Can you please retry and confirm the issue is resolved?

Thanks,
Matt

**Comment by salils123** [comment]
This is working now

**Comment by jennifermarsman** [comment]
Thanks!
