### ISSUE TITLE
Error while npm install -f

### ISSUE THREAD

**Issue by sagar2503** [microsoft/AzureSearch_JFK_Files#126]
I did below steps

**cd frontend
npm install -f**

And got below error

npm WARN deprecated material-ui-icons@1.0.0-beta.17: Use @material-ui/icons instead
npm ERR! code 1
npm ERR! path D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\gitrepo\\AzureSearch_JFK_Files\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\gitrepo\\AzureSearch_JFK_Files\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\gitrepo\AzureSearch_JFK_Files\frontend\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by ShaneOsborne** [comment]
For me I was running the latest version of Node but had to downgrade it to Version 14, a newer version may work than 14.
Also I installed Python 2 as well.

Hopefully a combination of above would work for you.

The whole project does need updating to new node packages, new .net packages, removing of obselete/non-supported and supporting latest version of Node and Python (it may work)

Will try to find some time to look into this

**Comment by Careyjmac** [comment]
Temporary fix applied in #128
