### ISSUE TITLE
front end not showing thumbnail 

### ISSUE THREAD

**Issue by abhisheksreesaila** [Microsoft/AzureSearch_JFK_Files#16]
![capture](https://user-images.githubusercontent.com/11252442/40375463-a8e201fe-5db9-11e8-80cf-7e9f892348da.JPG)

there is no error. and query works via "search explorer"

**Comment by Careyjmac** [comment]
Hi abhisheksreesaila,

Thank you for reporting this.  We found a bug that seems to have popped up over the last few weeks and have patched it.  If you pull from master and run the JfkInitializer again, everything should work as expected now and you will be able to use the website as intended.  Please feel free to reach out if you have any additional issues or questions.

Thanks,
Carey MacDonald
