### ISSUE TITLE
Indexer warning leading to blank thumbnails

### ISSUE THREAD

**Issue by stevekay72** [Microsoft/AzureSearch_JFK_Files#22]
Similar to issue #15 and issue #16 however:

I have the latest version of the code and am getting the same error as the original except that the Metadata is now upper cased for the 'm':

`Output field mapping target metadata: unable to select property while accessing '/document/hocrDocument/Metadata'\r\n"`

Strangely this only happens for some documents and not for all, and I am using my own data rather than the JFK files sample.

**Comment by rozele** [comment]
I am seeing this for all JFK documents.
