### ISSUE TITLE
No document preview on search screen and empty screen on toggle view

### ISSUE THREAD

**Issue by mtduman** [Microsoft/AzureSearch_JFK_Files#24]
I am having issue with document preview on search screen and empty screen on toggle view.

I downloaded the JFK code last month and followed the guide step by step. All services were up and working fine. I saw that, there is a new JFK code release last week and I applied it.  Since then, I am having issue with file preview. I can see the file names (docid-32395634.pdf,  photo.jpg), but no file preview and empty toggle view. When I click the file name, it brings up empty toggle view page.

After I got this problem, I generated all new services with different names. Applied new JFK code (only added key information on app.config) and got same problem again.

**FYI** - I deployed using the ARM template to a Basic  App Service plan and the Basic tier for Azure Search ( South Central location) and East US location for all other services

.
.
.

**Installed Node 10.5.0 Current**

**npm install**
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jfk-files@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 9590 packages in 16.77s
found 9 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**npm run build:prod**
run without any error or warning

**Comment by rozele** [comment]
I'm seeing something similar. One thing I noticed is a number of warnings from the Azure Search indexer:
```
    {
        "key": "https://azsjfkfiles.blob.core.windows.net/jfkfiles/oswald/docid-32348223.pdf",
        "message": "Output field mapping target metadata: unable to select property while accessing '/document/hocrDocument/Metadata'\r\n"
    },
```
The HOCR metadata (including the images) is supposed to be in the `metadata` property, but it looks like the skillset is having an issue when generating that property.

**Comment by rozele** [comment]
I think this is a dupe of #22.

**Comment by mtduman** [comment]
Thank you for help , it works

 JfkWebApiSkills/JfkInitializer/indexer.json

Replace:
            "sourceFieldName": "/document/hocrDocument/Metadata",
to:
            "sourceFieldName": "/document/hocrDocument/metadata",
