### ISSUE TITLE
After using private/no public access blob storage, the file preview and Toggle View gets blurry

### ISSUE THREAD

**Issue by mtduman** [Microsoft/AzureSearch_JFK_Files#28]
Hi, I changed the "**JFKFilesBlobStorageAccountConnectionString**" and "**JFKFilesBlobContainerName**” for a private blob storage and set the “Set Public Acces Level = **No public access**”. 

The JFK interface works fine, but the file preview and Toggle View shows blurry.

P.S.
I commented lines 137,138 and 139 at **Program.cs**
//	BlobContainerPermissions permissions = container.GetPermissions();
//	permissions.PublicAccess = BlobContainerPublicAccessType.Container;
//	await container.SetPermissionsAsync(permissions);

Many Thanks,
Matt

![image](https://user-images.githubusercontent.com/18400783/42451204-897e0d56-8354-11e8-9afe-e45eb1b89c06.png)

![image](https://user-images.githubusercontent.com/18400783/42451263-aa548c1c-8354-11e8-8678-419e4b07487a.png)

**Comment by mtduman** [comment]
I tried to use SAS (shared access signatures) also, but couldn’t make it work. I am still getting blurry screen for the files. Where and what format should I put SAS on the code ?

**Comment by Careyjmac** [comment]
Hi Matt,

Unfortunately, it is expected that if you make the created blob have no public access then the provided user interface will no longer work as it expects the files to be public in order for it to be able to retrieve them for displaying on the webpage.  If you want to use the website provided with this demo with your own private files, you may need to add additional steps to the website yourself for retrieving them.  Luckily, you should still be able to review the results of the Cognitive Search part of the app via the Azure Search service that was created for you using the [Azure portal](http://portal.azure.com) or the [Azure Search REST API](https://docs.microsoft.com/en-us/rest/api/searchservice/), you just won't have the nice web page to help make it more readable.

Using a SAS token will not solve the above problem related to the website, but just in case, there is [documentation here](https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage#Credentials) on the format that the token needs to be in in order for Azure Search to be able to index the data properly.

-Carey
