### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by mahajangaurav** [Microsoft/AzureSearch_JFK_Files#30]
Hi 

I am seeing these issues in the indexer:

 "key": "https://azsjfkfiles.blob.core.windows.net/jfkfiles/castro%20operation/docid-32105760.pdf",
        "errorMessage": "Skill #12: An existing connection was forcibly closed by the remote host\r\nSkill #12: An existing connection was forcibly closed by the remote host\r\nSkill #14: An existing connection was forcibly closed by the remote host\r\n

 Any idea what it could be?

Thanks!

**Comment by mahajangaurav** [comment]
To be clear, this is the error that I am seeing for the data source:
-----------------
[
    {
        "key": "https://azsjfkfiles.blob.core.windows.net/jfkfiles/castro%20operation/docid-32105760.pdf",
        "errorMessage": "Skill #12: An existing connection was forcibly closed by the remote host\r\nSkill #12: An existing connection was forcibly closed by the remote host\r\nSkill #14: An existing connection was forcibly closed by the remote host\r\nSkill #13: An existing connection was forcibly closed by the remote host\r\nSkill #14: An existing connection was forcibly closed by the remote host\r\nSkill #14: An existing connection was forcibly closed by the remote host\r\nSkill #14: An existing connection was forcibly closed by the remote host
---------------------------------
and then this repeats over and over for all subsequent requests for this skill set.

I am working on a customer demo for tomorrow and will request an urgent response.

Thanks!

**Comment by mgottein** [comment]
Mahajangaurav,

Unfortunately, the default Azure Function TLS settings are incompatible with custom skills. Please see this blog post for more information. https://blogs.msdn.microsoft.com/appserviceteam/2018/04/17/app-service-and-functions-hosted-apps-can-now-update-tls-versions/

Set your TLS minimum version to 1.0 for now. We are currently working on supporting TLS 1.2.

Thanks,
Matt

**Comment by Careyjmac** [comment]
I've merged a PR that will fix anyone who tries to deploy this from scratch, and I will revert that change once we officially support TLS 1.2.  Apologizes for any issues this has caused!

**Comment by mahajangaurav** [comment]
Thank you and appreciate your quick responses. I was able to get the demo working after setting the minimum TLS version to 1.0!

Interestingly, I was also able to use this solution to index some of my own documents and that worked great as well!
