### ISSUE TITLE
Error while searching on application

### ISSUE THREAD

**Issue by devPardeep** [Microsoft/AzureSearch_JFK_Files#36]
I'm getting error while searching on application. As checked in browser, the search button hitting the wrong URL: https://jfk-search-service-5qzqyqg22owne.search.windows.net, correct URL is https://jfk-site-eypd7z6qyiico.azurewebsites.net/.

Try to find out where is went wrong but did not found this "5qzqyqg22owne" in whole application.
Please help me to fix this problem.

Complete url is: OPTIONS https://jfk-search-service-5qzqyqg22owne.search.windows.net/indexes/jfkindex/docs?api-version=2017-11-11-Preview&searchMode=all&facet=entities,count:20&$count=true&$top=10&scoringProfile=demoBooster&highlight=text 0 ()

**Comment by Careyjmac** [comment]
It seems that you closed the issue so I assume you figured this out, but just in case anyone else encounters this problem, the solution is that if you delete and recreate the demo under a different resource group name, you will need to locally reset both the App.config file and the .env file that are a part of the project.  If you only reset the App.config file with the new credentials, the website credentials will not be correct, as the step to write to the .env file only works if that file is in the initial state from this repo.
