### ISSUE TITLE
Not showing my pdf file in search

### ISSUE THREAD

**Issue by devPardeep** [microsoft/AzureSearch_JFK_Files#38]
Demo is working fine for jfk pdf files but whenever i'm going to add my own pdf files or other documents in JFKFilesBlobStorageAccountConnectionString path its showing only search text without their images.

Also can we insert image or other word file directly to final imageblobstore container for searching from azure portal?
Or we need to follow same steps every time while uploading new file into the storage for refreshing the index? 

Thanks in advance for help :)

**Comment by briansmi** [comment]
This capability only works today with pdfs that have embedded images in them.  Many pdf's do not contain images and only contain text.  Can you confirm that your source pdfs contain images?

**Comment by devPardeep** [comment]
Thanks @briansmi  for reply. I got this point that it will work for only pdf with embedded images. But my other question are if I'm uploading JPG file to search blob folder directly then why its not searching that image.

**Comment by bikeg33k** [comment]
@Careyjmac I took your advice, and repointed the blob references in App.config to a blob that contains various reports/documents/powerpoints that we would like scanned.  Now when I search, the search results (left column) are correct, but the images on the right side all seem to show the same image, not the document or report like I would expect.  This is within 20 minutes of me uploading the blobs and redirecting the site to them.  
Is this something I just need to wait to watch it get corrected, or is there something else I need to trigger to have it index everything properly?

**Comment by dangolightly** [comment]
Hi, somewhere in the code the JFK files are uploaded and encoded with a GUID. It looks like the [FunctionName("image-store")] is the HTTP azure function that does the loading of the JFK files into the container, "string imageUri = await imageStore.UploadToBlob(imageData, Guid.NewGuid().ToString())". Is that correct? If so, where is that "https:.../image-store..." REST call made that iterates over the 900+ JFK files and uploads? I am just trying to reverse engineer so I can replace the JFK file loads with my own file loads. Hoping by changing at this level I don't have to rebuild everything. Maybe I am barking up the wrong tree? Thanks

**Comment by Careyjmac** [comment]
Closing as this seems to have been resolved and has not had discussion in several months.

Also, as some additional context in case anyone else has PDFs without embedded images but would still like to process them using the demo, we how have [an indexer option called generateNormalizedImagePerPage](https://docs.microsoft.com/en-us/azure/search/cognitive-search-concept-image-scenarios#get-normalized-images) that will convert each page of the PDF to be an image.  Of course this means that the OCRed text may not be as accurate as the original native text, but this is the only way today to get the hOCR part of the demo to work properly as we need to perform OCR to be able to know the bounding boxes of each word in the file.

**Comment by prototypejohn** [comment]
I have the same problem. But I started the demo from the start, with my own blobstorage with my own documents. Some show a preview but others won't. And yet, as bikeg33k, searched words are ok and points to the documents.
