### ISSUE TITLE
Hos is Azure ML implemented in this JFK sample?

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/AzureSearch_JFK_Files#44]
In one of readme.md file, it is mentioned Azure ML would soon be integrated in this sample. May I know if it is implemented in this, and where I can find it?

**Comment by Careyjmac** [comment]
Today Azure ML is not a part of this sample, however, you can check out our [new sample repo for Azure knowledge mining](https://github.com/Azure-Samples/azure-search-knowledge-mining/tree/master/03%20-%20Data%20Science%20and%20Custom%20Skills/AML%20Custom%20Skill%20Template) to go through a tutorial on how to generate your own Azure ML custom skill for use with cognitive search.
