### ISSUE TITLE
Error in CreateSkillSet

### ISSUE THREAD

**Issue by mahajangaurav** [Microsoft/AzureSearch_JFK_Files#49]
Hi 
I used to be able to initialize perfectly fine earlier but am now receiving this error when running the initializer. The error shows up in **CreateSkillSet** when getting the **AzureFunctionHostKey** here:

**_azureFunctionHostKey = await KeyHelper.GetAzureFunctionHostKey(_httpClient);**

Any thoughts?

{"Message":"An error has occurred.","ExceptionMessage":"Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetMasterKeyAsync>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 213\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetMasterKey>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 121"}

**Comment by mahajangaurav** [comment]
Update for anyone facing this issue: I wen to the "Application settings" for the function app created through the deployment and did exactly what the error message was asking me to do - added a new Application setting called "AzureWebJobsSecretStorageType" and gave it the value "Files". This resolved the issue. I am leaving the issue open in case the deployment needs to be updated.
Thanks!

**Comment by Careyjmac** [comment]
Added this setting to the ARM template so that it will be there automatically from now on, thanks!
