### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by TanShv** [microsoft/AzureSearch_JFK_Files#52]
Trying to make the code run in IE11, there are some JS errors, probably coming from react. Is this can be a issue of react-redux version issue or anything?
Here is one of the error, I am not able to understand: 
Unable to get property 'Component' of undefined or null reference

**Comment by Careyjmac** [comment]
Closing as this seems to have been resolved and has not had discussion in several months.  I suggest using a different browser with the demo if possible, I have not tested IE myself.
