### ISSUE TITLE
your worker runtime is not set error

### ISSUE THREAD

**Issue by AlexFiala** [Microsoft/AzureSearch_JFK_Files#57]
@Careyjmac I'm also seeing an issue during build of the frontend, after step #12.  I receive a "your worker runtime is not set" error that advises "run func settings add functions_worker_runtime"

Any guidance on this error?  It appears to have been an issue in the Azure Functions code and was addressed in 2018.  But the error persists.

**Comment by Careyjmac** [comment]
I just did a test with my latest branch (updatesAndFixes) after a "git clean -xdf" to ensure I was on a clean repo and everything worked as expected.  I would suggest trying that as well.  My PR to merge the changes from that branch into master should go in either later today or tomorrow.

**Comment by AlexFiala** [comment]
Thanks for the quick reply @Careyjmac.  I just ran your latest build and tried to step through the demo again.

Is the below the expected console application output following build?  It ends, and I run the NPM commands, but when I return to this console app and press any key, nothing happens and no URL is supplied for the demo.

your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.
Please run `func settings add FUNCTIONS_WORKER_RUNTIME <option>` or add FUNCTIONS_WORKER_RUNTIME to your local.settings.json
Available options: dotnet, node, python

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.4.299 Commit hash: 0f105e9bc6e2faed71e8521d7541a909a6dcc389)
Function Runtime Version: 2.0.12285.0
Skipping 'SearchServiceName' from local settings as it's already defined in current environment variables.
Skipping 'SearchServiceApiKey' from local settings as it's already defined in current environment variables.
Skipping 'BlobStorageAccountConnectionString' from local settings as it's already defined in current environment variables.
[2/5/2019 4:41:40 AM] Starting Rpc Initialization Service.
[2/5/2019 4:41:40 AM] Initializing RpcServer
[2/5/2019 4:41:40 AM] Building host: startup suppressed:False, configuration suppressed: False
[2/5/2019 4:41:40 AM] Reading host configuration file 'C:\jfk\JfkWebApiSkills\JfkWebApiSkills\bin\Debug\netstandard2.0\host.json'
[2/5/2019 4:41:40 AM] Host configuration file read:
[2/5/2019 4:41:40 AM] {
[2/5/2019 4:41:40 AM]   "version": "2.0"
[2/5/2019 4:41:40 AM] }
[2/5/2019 4:41:40 AM] Initializing Host.
[2/5/2019 4:41:40 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[2/5/2019 4:41:40 AM] LoggerFilterOptions
[2/5/2019 4:41:40 AM] {
[2/5/2019 4:41:40 AM]   "MinLevel": "None",
[2/5/2019 4:41:40 AM]   "Rules": [
[2/5/2019 4:41:40 AM]     {
[2/5/2019 4:41:40 AM]       "ProviderName": null,
[2/5/2019 4:41:40 AM]       "CategoryName": null,
[2/5/2019 4:41:40 AM]       "LogLevel": null,
[2/5/2019 4:41:40 AM]       "Filter": "<AddFilter>b__0"
[2/5/2019 4:41:40 AM]     },
[2/5/2019 4:41:40 AM]     {
[2/5/2019 4:41:40 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/5/2019 4:41:40 AM]       "CategoryName": null,
[2/5/2019 4:41:40 AM]       "LogLevel": "None",
[2/5/2019 4:41:40 AM]       "Filter": null
[2/5/2019 4:41:40 AM]     },
[2/5/2019 4:41:40 AM]     {
[2/5/2019 4:41:40 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/5/2019 4:41:40 AM]       "CategoryName": null,
[2/5/2019 4:41:40 AM]       "LogLevel": null,
[2/5/2019 4:41:40 AM]       "Filter": "<AddFilter>b__0"
[2/5/2019 4:41:40 AM]     }
[2/5/2019 4:41:40 AM]   ]
[2/5/2019 4:41:40 AM] }
[2/5/2019 4:41:40 AM] FunctionResultAggregatorOptions
[2/5/2019 4:41:40 AM] {
[2/5/2019 4:41:40 AM]   "BatchSize": 1000,
[2/5/2019 4:41:40 AM]   "FlushTimeout": "00:00:30",
[2/5/2019 4:41:40 AM]   "IsEnabled": true
[2/5/2019 4:41:40 AM] }
[2/5/2019 4:41:40 AM] SingletonOptions
[2/5/2019 4:41:40 AM] {
[2/5/2019 4:41:40 AM]   "LockPeriod": "00:00:15",
[2/5/2019 4:41:40 AM]   "ListenerLockPeriod": "00:00:15",
[2/5/2019 4:41:40 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2/5/2019 4:41:40 AM]   "LockAcquisitionPollingInterval": "00:00:05",
[2/5/2019 4:41:40 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2/5/2019 4:41:40 AM] }
[2/5/2019 4:41:40 AM] Starting JobHost
[2/5/2019 4:41:41 AM] Starting Host (HostId=console3-1995750749, InstanceId=e3b5a683-9365-4497-8c8d-3723efefcab6, Version=2.0.12285.0, ProcessId=11076, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[2/5/2019 4:41:41 AM] Loading functions metadata
[2/5/2019 4:41:41 AM] 5 functions loaded
[2/5/2019 4:41:41 AM] WorkerRuntime: dotnet. Will shutdown other standby channels
[2/5/2019 4:41:41 AM] Generating 5 job function(s)
[2/5/2019 4:41:41 AM] Found the following functions:
[2/5/2019 4:41:41 AM] Microsoft.CognitiveSearch.WebApiSkills.JfkWebApiSkills.GetFacetGraphNodes
[2/5/2019 4:41:41 AM] Microsoft.CognitiveSearch.WebApiSkills.JfkWebApiSkills.RunHocrGenerator
[2/5/2019 4:41:41 AM] Microsoft.CognitiveSearch.WebApiSkills.JfkWebApiSkills.RunImageStore
[2/5/2019 4:41:41 AM] Microsoft.CognitiveSearch.WebApiSkills.JfkWebApiSkills.RunCryptonymLinker
[2/5/2019 4:41:41 AM] Microsoft.CognitiveSearch.WebApiSkills.JfkWebApiSkills.RunCryptonymLinkerForLists
[2/5/2019 4:41:41 AM]
[2/5/2019 4:41:41 AM] Host initialized (442ms)
[2/5/2019 4:41:41 AM] Host started (458ms)
[2/5/2019 4:41:41 AM] Job host started
Hosting environment: Production
Content root path: C:\jfk\JfkWebApiSkills\JfkWebApiSkills\bin\Debug\netstandard2.0
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        facet-graph-nodes: [GET] http://localhost:7071/api/facet-graph-nodes

        hocr-generator: [POST] http://localhost:7071/api/hocr-generator

        image-store: [POST] http://localhost:7071/api/image-store

        link-cryptonyms: [POST] http://localhost:7071/api/link-cryptonyms

        link-cryptonyms-list: [POST] http://localhost:7071/api/link-cryptonyms-list

[2/5/2019 4:41:46 AM] Host lock lease acquired by instance ID '0000000000000000000000002613A990'.

**Comment by AlexFiala** [comment]
@Careyjmac , so I added a "FUNCTIONS_WORKER_RUNTIME" set to "dotnet" and this error did not present again when I ran the build again.  However, the console application is still showing the same output as above.  The console app again ends with the same "[2/5/2019 4:41:46 AM] Host lock lease acquired by instance ID '0000000000000000000000002613A990'."

I also ran the npm commands after this, to see what'd happen, and have the below return:

What is the expected console app return and npm return?

Microsoft Windows [Version 10.0.17134.556]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\alex>cd c:\jfk

c:\jfk>cd frontend

c:\jfk\frontend>npm install
npm WARN ajv-keywords@3.3.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jfk-files@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 11154 packages in 16.312s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

c:\jfk\frontend>npm run build:prod

> jfk-files@1.0.0 build:prod c:\jfk\frontend
> npm run clean && env-cmd .env cross-env NODE_ENV=production webpack -p --config=webpack.prod.config.js


> jfk-files@1.0.0 clean c:\jfk\frontend
> rimraf dist


[at-loader] Using typescript@2.9.2 from typescript and "tsconfig.json" from c:/jfk/frontend/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.009 sec.
Hash: afb32ec811ff17712ac4
Version: webpack 3.8.1
Time: 39599ms
                             Asset       Size  Chunks                    Chunk Names
        android-chrome-192x192.png    6.76 kB          [emitted]
                 assets/img/bg.jpg     178 kB          [emitted]
       assets/fonts/jfk-icons.woff    2.94 kB          [emitted]
        assets/fonts/jfk-icons.svg    7.84 kB          [emitted]
 assets/img/jfk-files-scenario.png     472 kB          [emitted]  [big]
  assets/svg/azure-search.logo.svg     1.3 kB          [emitted]
    7b8604b95e79bdbd3c86.vendor.js    1.93 MB       0  [emitted]  [big]  vendor
       ebc4f9391c59efbbc972.app.js     161 kB       1  [emitted]         app
 b69f9f7404bec9a48fb8.appStyles.js  440 bytes       2  [emitted]         appStyles
  b3f2fc729914331e1103.manifest.js    1.44 kB       3  [emitted]         manifest
      ebc4f9391c59efbbc972.app.css    24.1 kB       1  [emitted]         app
b69f9f7404bec9a48fb8.appStyles.css    5.03 kB       2  [emitted]         appStyles
                        index.html    21.3 kB          [emitted]
        assets/fonts/jfk-icons.ttf    2.86 kB          [emitted]
              apple-touch-icon.png    6.21 kB          [emitted]
                mstile-144x144.png    4.36 kB          [emitted]
                 favicon-16x16.png  668 bytes          [emitted]
                 browserconfig.xml  246 bytes          [emitted]
                 favicon-32x32.png    1.09 kB          [emitted]
                  mstile-70x70.png    2.92 kB          [emitted]
        android-chrome-512x512.png    21.1 kB          [emitted]
                mstile-310x150.png    4.57 kB          [emitted]
                       favicon.ico    15.1 kB          [emitted]
                  site.webmanifest  426 bytes          [emitted]
                mstile-310x310.png    9.55 kB          [emitted]
                mstile-150x150.png    4.25 kB          [emitted]
 [245] ./pages/search-page/index.ts 125 bytes {1} [built]
 [419] ./pages/home-page/home-page.container.tsx 2.84 kB {1} [built]
 [659] ./pages/detail-page/index.ts 125 bytes {1} [built]
 [662] ./theme/main.scss 432 bytes {2} [built]
 [699] multi ./app.tsx 28 bytes {1} [built]
 [700] ./app.tsx 417 bytes {1} [built]
 [981] ./app.router.tsx 2.59 kB {1} [built]
 [999] ./pages/home-page/index.ts 115 bytes {1} [built]
[1088] ../node_modules/moment/locale ^\.\/.*$ 3.07 kB {0} [optional] [built]
[1451] ./pages/detail-page/detail-page.route.tsx 285 bytes {1} [built]
[1455] ./pages/search-page/search-page.route.tsx 274 bytes {1} [built]
[1457] ./theme/index.ts 32 bytes {1} [built]
[1458] ./theme/theme.ts 1.13 kB {1} [built]
[1459] multi ./theme/main.scss 28 bytes {2} [built]
[1460] multi babel-polyfill material-ui material-ui-icons material-ui-pickers moment paginator qs react react-dom react-router-dom d3 148 bytes {0} [built]
    + 2605 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ../node_modules/html-webpack-plugin/lib/loader.js!./index.html 21.3 kB {0} [built]
        + 3 hidden modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!theme/main.scss:
                          Asset     Size  Chunks             Chunk Names
              assets/img/bg.jpg   178 kB          [emitted]
     assets/fonts/jfk-icons.ttf  2.86 kB          [emitted]
    assets/fonts/jfk-icons.woff  2.94 kB          [emitted]
     assets/fonts/jfk-icons.svg  7.84 kB          [emitted]
       [0] ../node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1,"localIdentName":"[local]__[name]___[hash:base64:5]"}!../node_modules/resolve-url-loader!../node_modules/sass-loader/lib/loader.js!./theme/main.scss 1.83 kB {0} [built]
       [3] ./assets/img/bg.jpg 63 bytes {0} [built]
       [4] ./assets/fonts/jfk-icons.eot 4.11 kB {0} [built]
       [5] ./assets/fonts/jfk-icons.ttf 72 bytes {0} [built]
       [6] ./assets/fonts/jfk-icons.woff 73 bytes {0} [built]
       [7] ./assets/fonts/jfk-icons.svg 72 bytes {0} [built]
        + 2 hidden modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/search-page.style.scss:
       [0] ../node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1,"localIdentName":"[local]__[name]___[hash:base64:5]"}!../node_modules/resolve-url-loader!../node_modules/sass-loader/lib/loader.js!./pages/search-page/search-page.style.scss 779 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/detail-page/detail-page.style.scss:
       [0] ../node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1,"localIdentName":"[local]__[name]___[hash:base64:5]"}!../node_modules/resolve-url-loader!../node_modules/sass-loader/lib/loader.js!./pages/detail-page/detail-page.style.scss 1.32 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/pagination/pagination.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/spacer/spacer.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/horizontal-separator/horizontal-separator.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/footer/footer.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/facets/facet-view.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/graph/graph-view.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/page-bar/page-bar.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/item/item-collection-view.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/drawer/drawer.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/search/search.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/detail-page/components/toolbar/toolbar.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/search/autocomplete.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/facets/facet-item.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/drawer/drawer-bar.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/page-bar/view-mode-toggler.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/placeholder/dialog.styles.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/placeholder/azure-button.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/item/item.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/hocr-document/hocr-document.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/hocr-preview/hocr-preview.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/hocr-proofreader/hocr-proofreader.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/facets/facet-body.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/placeholder/link.styles.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/facets/facet-header.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/menu-button/menu-button.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/vertical-separator/vertical-separator.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/logo-jfk/style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/logo-microsoft/style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/hocr-preview/hocr-node.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/chevron/chevron.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/hocr-preview/hocr-page.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/selection-controls/year-picker.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/search-page/components/selection-controls/checkbox-list.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!common/components/hocr/tooltip/tooltip.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/home-page/home-page.style.scss:
       [0] ../node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1,"localIdentName":"[local]__[name]___[hash:base64:5]"}!../node_modules/resolve-url-loader!../node_modules/sass-loader/lib/loader.js!./pages/home-page/home-page.style.scss 1.84 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/home-page/components/caption/caption.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/home-page/components/search/search-button.style.scss:
       2 modules
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--8-2!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js!pages/home-page/components/search/search-input.style.scss:
       2 modules

c:\jfk\frontend>

**Comment by Careyjmac** [comment]
Your website build looks right, but I know what the problem is now.  Make sure you are running the "JfkInitializer" project, NOT the "JfkWebApiSkills" project.  See step 7, the default project is usually JfkWebApiSkills and you have to manually select JfkInitializer from the dropdown next to the run button (see the picture from step 12 for what I mean).  It seems like you likely are running the JfkWebApiSkills, which just spins up the function instance locally, which is already deployed remotely by the arm template for you.

**Comment by AlexFiala** [comment]
@Careyjmac , wow don't I feel like a noob!

Thanks Carey :D
