### ISSUE TITLE
skillset #10 is depreciated

### ISSUE THREAD

**Issue by stephenhallfr** [Microsoft/AzureSearch_JFK_Files#60]
Hi

The skill set #10 NamedEntityRecognitionSkill is depreciated.

https://docs.microsoft.com/en-us/azure/search/cognitive-search-skill-deprecated

needs to replace NamedEntityRecognitionSkill  by EntityRecognitionSkill
and entities by namedEntities

**Comment by Careyjmac** [comment]
Make sure you are using the latest version from the master branch.  We made the change several months ago to update the demo to use the new skill: https://github.com/Microsoft/AzureSearch_JFK_Files/blob/2d20a0e634851d6e6a017a24e97e5098ed65f23d/JfkWebApiSkills/JfkInitializer/skillset.json#L204
