### ISSUE TITLE
JFK Files connection string is not functional.

### ISSUE THREAD

**Issue by jbarntish** [Microsoft/AzureSearch_JFK_Files#63]
Running the JfkInitializer is producing 400 error on the CreateIndexer() step. Replacing the JFKFilesBlobStorageAccountConnectionString connection string value with a different one seems to fix it. 

Is there another place to source the content?

**Comment by Careyjmac** [comment]
Apologizes for this, we originally set it up to expire after a year, and that year has now passed.  I will push an update for the connection string with an updated sas later today.

**Comment by Careyjmac** [comment]
Should be fixed now.
