### ISSUE TITLE
Still pointing to JFK files after changing all settings.

### ISSUE THREAD

**Issue by marklmvalencia** [microsoft/AzureSearch_JFK_Files#65]
I have changed all JFK related settings in the AppConfig.cs and Config.cs files to point to our company's Search Service, Storage Containers, Blobs, etc., but I am still pointed to the JFK files. The only thing left unchanged are the Azure Web App instance and Azure Function instance. Am I missing something?

**Comment by Careyjmac** [comment]
Did you make these changes after building and deploying the website?

As part of creating the website, we write several of the secrets to a file for the website doing a find and replace type write, meaning that once you do it for the first time, if you want to change any of the secrets, you must reset that file to its original state for the find and replace of the new secrets to work.  The file that you would have to reset before running the demo with different secrets would be the [frontend/.env](https://github.com/microsoft/AzureSearch_JFK_Files/blob/master/frontend/.env) file.

Also, just as a sanity check, if you are trying to point the demo at a different set of files, you likely need to change [the provided JFKFilesBlobStorageAccountConnectionString and JFKFilesBlobContainerName variables in the App.config file](https://github.com/microsoft/AzureSearch_JFK_Files/blob/613181e17929a0bf144fd139be2924215c0d6d7b/JfkWebApiSkills/JfkInitializer/App.config#L29) as well, which can be easy to miss.  And you mentioned replacing the secrets in the Config.cs for the Azure Functions, if you are looking to change those details, you will also need to redeploy the Azure Function, as we deploy it with the secrets for the resources deployed with the initial ARM template, and running the JfkInitializer does not redeploy the Azure Function itself.

**Comment by marklmvalencia** [comment]
Yes I made the changes after building and deploying the website. Instead of modifying the front/.env file, I opted to make a fresh state of the solution and put our settings in the AppConfig.cs and Config.cs files before building and deploying the website. It is working well now. Thanks for your advice.
