### ISSUE TITLE
How to replace JFK logo images

### ISSUE THREAD

**Issue by marklmvalencia** [microsoft/AzureSearch_JFK_Files#66]
I tried to replace all the image (PNG) in the frontend folder but it is still showing the JFK files logo. Any tips how to change this?

**Comment by Careyjmac** [comment]
Are you saying this with the intent of using this demo for other document sources?  That is fine, its just not the main public intent of the demo, so I don't have any strong guidance on how to help you de-JFK the website for other use cases.  If you are extremely interested in this scenario, please feel free to reach out to me at cmacdo@microsoft.com and I can see what I can do to help.
