### ISSUE TITLE
Creating Index ended in error

### ISSUE THREAD

**Issue by fhe-fr** [microsoft/AzureSearch_JFK_Files#68]
eleting Index, Indexer and SynonymMap if they exist...
Creating Blob Container for Image Store Skill...
Creating Skill Set...
Creating Synonym Map...
Creating Index...
Create Index response:
{"error":{"code":"","message":"The request is invalid. Details: definition : The synonym map 'cryptonyms' specified in the field 'text' does not exist.\r\n"}}
Something went wrong.
Press any key to exit.

**Comment by Careyjmac** [comment]
Does this repro consistently?  It sounds like a race condition as we create the synonym map immediately before creating the index, so perhaps the change hadn't fully propgated on the backend by the time you attempted to create the index.

**Comment by fhe-fr** [comment]
Can we add a wait() or sleep() some where in the code before starting to create the index?

**Comment by fhe-fr** [comment]
I add this code:
private static async Task<bool> CreateIndex()
        {
            Console.WriteLine("Creating Index...");
            Console.WriteLine("Sleeping for 10 sec...");
            System.Threading.Thread.Sleep(10000);
            Console.WriteLine("Continue Creating Index...");
            try
               {
But get the same error:
Deleting Index, Indexer and SynonymMap if they exist...
Creating Blob Container for Image Store Skill...
Creating Skill Set...
Creating Synonym Map...
Creating Index...
Sleeping for 10 sec...
Continue Creating Index...
Create Index response:
{"error":{"code":"","message":"The request is invalid. Details: definition : The synonym map 'cryptonyms' specified in the field 'text' does not exist.\r\n"}}
Something went wrong.
Press any key to exit.

**Comment by fhe-fr** [comment]
Here the issue:
 private static async Task<bool> CreateSynonyms()
        {
            Console.WriteLine("Creating Synonym Map...");

            // Add implementation here

            return true;
        }
There is no code to create the CreateSynonyms

**Comment by Careyjmac** [comment]
Not sure where you see the code, the implementation for creating the synonymmaps is definitely there if you pull the latest from master: https://github.com/microsoft/AzureSearch_JFK_Files/blob/2adaca178394adea5bc813f782110215f24dab26/JfkWebApiSkills/JfkInitializer/Program.cs#L232

**Comment by fhe-fr** [comment]
There is 2 repository on github for JFK lab:
https://github.com/microsoft/ailab/tree/master/JFKFiles
and
https://github.com/microsoft/AzureSearch_JFK_Files
in the first code is missing.
