### ISSUE TITLE
error in the build of the front end

### ISSUE THREAD

**Issue by val21bergman** [microsoft/AzureSearch_JFK_Files#78]
In attempting to build the front end, I have run into issues with 
npm install
npm run build:prod

After further inspection, it was because I ran a cmd versus a node cmd window.  Consider clarifying the instructions.

**Comment by Careyjmac** [comment]
It is noted in the README that you must have Node.js installed for this demo to work.  Do you mean to say that npm wasn't on your PATH and that's why it didn't work?  I build the demo from a regular cmd and have never had any issues, but I also have npm on my PATH variable.
