### ISSUE TITLE
No index.json in master branch

### ISSUE THREAD

**Issue by johniwasz** [microsoft/AzureSearch_JFK_Files#84]
The documentation references an index.json file at the end of the github landing page documentation.

> 2. You can add the "enriched" field to your index to see detailed output of all skills that are run. Details on how to do this can be found here. You will be making this change in ./JfkWebApiSkills/JfkInitializer/index.json.

The index.json file is not present in the master branch. It is present in the json branch. It looks like a merge is needed.

**Comment by Careyjmac** [comment]
This is because we have since updated the master branch to use the .NET SDK support we have for Azure Cognitive Search instead of relying on our REST api directly.  The README should be updated to mention that the correct place to make the update would now be SearchResource.GetIndex method.

**Comment by Careyjmac** [comment]
This README bug is fixed in #86
