### ISSUE TITLE
AzureSearch_JKF_Files Visual Code Failed

### ISSUE THREAD

**Issue by Hrashid789** [microsoft/AzureSearch_JFK_Files#88]
I have getting the below error messege when try running the initializing code. Appreciate if someone can help.

![image](https://user-images.githubusercontent.com/59919959/78897157-6a863300-7a7a-11ea-8ac1-893235955f31.png)
![image](https://user-images.githubusercontent.com/59919959/78897450-dd8fa980-7a7a-11ea-9848-b84055ca8d28.png)

**Comment by Careyjmac** [comment]
This looks like errors with the required NuGet packages not being downloaded/installed correctly.  Please reference the following documentation and see if it helps:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting

**Comment by Hrashid789** [comment]
Thank You Carey for your response. 
I tried this already; it does not help in any way to troubleshoot the error. It is sad to see that such a great lab does not work. I hope that someone can support in resolving this issue.

**Comment by Hrashid789** [comment]
I have resolved the **newtonsoft** but I am still stuck at the namespace issue.

**Comment by Hrashid789** [comment]
Thank You Corom and Carey for your support in resolving this issue.
