### ISSUE TITLE
Not able to run the react (frontend) solution from the repo even after following the setup instructions

### ISSUE THREAD

**Issue by pwcrohit** [microsoft/AzureSearch_JFK_Files#92]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:prod'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle jfk-files@1.0.0~prebuild:prod: jfk-files@1.0.0
6 info lifecycle jfk-files@1.0.0~build:prod: jfk-files@1.0.0
7 verbose lifecycle jfk-files@1.0.0~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle jfk-files@1.0.0~build:prod: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\r0hit\Project\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\frontend\node_modules\.bin;E:\app\harshb020\product\11.1.0\db_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\WinZip\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;;C:\Users\IN_RDP_USER_02\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\IN_RDP_USER_02\AppData\Roaming\npm
9 verbose lifecycle jfk-files@1.0.0~build:prod: CWD: D:\r0hit\Project\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\frontend
10 silly lifecycle jfk-files@1.0.0~build:prod: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run clean && env-cmd .env cross-env NODE_ENV=production webpack -p --config=webpack.prod.config.js'
10 silly lifecycle ]
11 silly lifecycle jfk-files@1.0.0~build:prod: Returned: code: 2  signal: null
12 info lifecycle jfk-files@1.0.0~build:prod: Failed to exec build:prod script
13 verbose stack Error: jfk-files@1.0.0 build:prod: `npm run clean && env-cmd .env cross-env NODE_ENV=production webpack -p --config=webpack.prod.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jfk-files@1.0.0
15 verbose cwd D:\r0hit\Project\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\frontend
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 2
22 error jfk-files@1.0.0 build:prod: `npm run clean && env-cmd .env cross-env NODE_ENV=production webpack -p --config=webpack.prod.config.js`
22 error Exit status 2
23 error Failed at the jfk-files@1.0.0 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by mariotzki** [comment]
Same here. Getting the error below

![image](https://user-images.githubusercontent.com/4824063/88713772-a6e4aa00-d0d0-11ea-9166-bc4dc7d649f6.png)
