### ISSUE TITLE
Unable to Authenticate Function App and Web App Services

### ISSUE THREAD

**Issue by kavyasriV** [microsoft/AzureSearch_JFK_Files#97]
I am a beginner with azure services. I have replicated all the steps demonstrated in this example.

I am unable to authenticate Function App and Web App from the code here. can someone help me with this.

**Comment by Careyjmac** [comment]
Can you share the exact error message that is occurring when you run the JfkInitializer project?  It would also be helping if you set the DebugMode boolean flag to true to get additional details on what is going wrong.

**Comment by kavyasriV** [comment]
I have set debug mode to true and tried to debug the code. I am getting 401 unauthorized error while authenticating Function App and Web App. I am confused if i am passing wrong Username and Password through config. Which Username and Password to provide here.

**Comment by Careyjmac** [comment]
You should be getting the username and password as part of step 9 of the instructions in the README (i.e. they will be output as part of the deployment template so you don't need to search for them).  Here are some additional instructions on where to find these credentials in the Azure portal if needed for some reason: https://docs.microsoft.com/en-us/azure/app-service/deploy-configure-credentials#appscope

**Comment by kavyasriV** [comment]
I was trying multiple things and i tried these FTP Creds also. i tried app creds and user creds also but nothing seems to work.

**Comment by kavyasriV** [comment]
how can i remove user creds from app service ?

**Comment by Careyjmac** [comment]
If you deploy and use the apps that created as part of the instructions as explicitly written in this repo, then you should have no issues. If you are trying to use an app service that you created separately, there are no guarantees on it being able to work.

**Comment by kavyasriV** [comment]
Thank you. Issue is now solved 👍
